### ISSUE TITLE
In HTTP Context apk upload will not work

### ISSUE THREAD

**Issue by anantshri** [Pithus/bazaar#123]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/236843/209809484-5724ae89-a9e8-41d9-9e79-a5cc2f6c8773.png">

```
            return crypto.subtle.digest('SHA-256', result);
```

as per https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest 
"This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest#browser_compatibility)."

Hence this makes pithus non usable on http connection.

It should not matter but we are promoting our docker compose via which creates a http instance only.

Browser used : chromium on mac

**Comment by evilcel3ri** [comment]
Ok thanks for the find, let me ask you more questions to give more context:

* did you run that on the bare bone local.yml and master branch? Did you make any modifications?
* did that error prevented you from using the tool? Was the upload successful nevertheless?

**Comment by evilcel3ri** [comment]
That's weird, running as http://localhost:8001?

**Comment by anantshri** [comment]
yup it might be browser dependent i will try on other browsers in a few minute and will update.

**Comment by evilcel3ri** [comment]
Fixed.

The host was running on a custom fqdn and localhost was exempted. When running on a custom fqdn, a SSL certificate should be provided. Otherwise, run Pithus on http://localhost:8001 on your own machine.
