### ISSUE TITLE
Problem with Docker Compose installation

### ISSUE THREAD

**Issue by b-u-g-s** [Pithus/bazaar#15]
Hi,

I am trying to install your framework but the docker compose installation doesn't seem to work.
I am on a Mac, running Docker version 3.3.2 and compose 1.29.1
It is a brand new install of Docker, with no images, nothing.

I git clone bazaar
I ran the docker-compose -f local.yml build
Everything seems to go ok...
However I noticed it starts with:
redis uses an image, skipping
mailhog uses an image, skipping
elasticsearch uses an image, skipping
mobsf uses an image, skipping
kibana uses an image, skipping
minio uses an image, skipping
Building postgres
....
then it build everything and there are no error.

But if I then go to the URL listed in your instruction (http://localhost:8001) nothing happens...

If I look in the docker dashboard, I can see no apps have started.
But there are 3x images:
- backend_local_worker
- bazaar_local_django
- bazaar_production_posgres

If I start them manually, they each exit with a very quick error:
- backend_local_worker
 Error:
/entrypoint: line 10: POSTGRES_USER: unbound variable

- bazaar_local_django
Error:
/entrypoint: line 10: POSTGRES_USER: unbound variable

- bazaar_production_posgres
Error: 
Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
connections without a password. This is *not* recommended.
See PostgreSQL documentation about "trust":
https://www.postgresql.org/docs/current/auth-trust.html

So it looks I am missing some steps...
I am not too familiar with docker and docker-compose but should I be running some docker-compose up first?

Any help welcome!
Thanks.
Bugs.

**Comment by b-u-g-s** [comment]
Ok, so I did more troubleshooting/testing. 
After I did all I mentioned in the previous post, I renamed local.yml into compose.yml
and then ran
docker-compose up

It started downloading all the images that were skipped previously.
And everything seems to start
The bazaar app is created and started.
All is ok apart from the elasticsearch... with keep existing (137)
and the logs show the following error:
kibana_1         | {"type":"log","@timestamp":"2021-05-05T19:03:25Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}

when I try to go to localhost:8001 I get a connection error:

<h1 style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; padding: 0px; margin: 0px; font-weight: normal; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: sans-serif; background-color: rgb(255, 255, 204);">ConnectionError at /</h1><pre class="exception_value" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); background-color: rgb(255, 255, 204);">ConnectionError(&lt;urllib3.connection.HTTPConnection object at 0x7fd591216d90&gt;: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(&lt;urllib3.connection.HTTPConnection object at 0x7fd591216d90&gt;: Failed to establish a new connection: [Errno -2] Name or service not known)</pre>

Request Method: | GET
-- | --
http://localhost:8001/
3.0.11
ConnectionError
ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd591216d90>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd591216d90>: Failed to establish a new connection: [Errno -2] Name or service not known)
/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py in perform_request, line 264
/usr/local/bin/python
3.8.10
['.',  '/usr/local/bin',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/site-packages',  '/app/bazaar']

Any reasons why elastic search is failing?
frustrating as it seems I am very close of getting this working now!! ;)

**Comment by U039b** [comment]
Hi!
Sorry for the inconvenience. Sometimes at the first startup ElasticSearch fails. Could you try to restart the ElasticSearch service?
```
docker-compose -f local.yml restart elasticsearch
```

**Comment by b-u-g-s** [comment]
Hi,
Tried that, and on the command line it says "done"
In the docker dashboard I can see it starting but then stopping immediately (i.e. a few seconds). No logs are generated.
I waited for about 10 minutes, restart the elastic search... and still nothing.

**Comment by b-u-g-s** [comment]
Ok so I fixed the problem 
Basically, Elasticsearch was exiting with code 137, apparently it is often linked to not enough memory being allocated with Docker... so I changed that and allocated at least 4Gb and restarted the app. It works :)

But I seem to have found another bug so I will add another issue :)

Also... the instructions as mentioned to get started did not work for me, and I had to do a docker compose up to get the app started
