### ISSUE TITLE
Sign In does not work - SocialApp matching query does not exist

### ISSUE THREAD

**Issue by b-u-g-s** [Pithus/bazaar#16]
Hi,

I just installed a new test env with docker compose.
The app starts
I can get to the home page
I click on Sign In then Signing with Github and then I get the following error:

Environment:

Request Method: GET
Request URL: http://localhost:8001/accounts/github/login/?process=login

Django Version: 3.0.11
Python Version: 3.8.10
Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.forms',
 'crispy_forms',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.github',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'django_q',
 'minio_storage',
 'bazaar.users.apps.UsersConfig',
 'bazaar.core',
 'bazaar.front',
 'compressor',
 'django_extensions']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.common.BrokenLinkEmailsMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 77, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 105, in dispatch
    app = provider.get_app(self.request)
  File "/usr/local/lib/python3.8/site-packages/allauth/socialaccount/providers/base.py", line 49, in get_app
    return adapter.get_app(request, self.id)
  File "/usr/local/lib/python3.8/site-packages/allauth/socialaccount/adapter.py", line 207, in get_app
    app = SocialApp.objects.get_current(provider, request)
  File "/usr/local/lib/python3.8/site-packages/allauth/socialaccount/models.py", line 32, in get_current
    app = self.get(sites__id=site.id, provider=provider)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /accounts/github/login/
Exception Value: SocialApp matching query does not exist.

**Comment by christalib** [comment]
Hi! Thank you for trying out Pithus 😁 

So as you see the base the URL is localhost, so the social app connection won't really work in a local installation. But there is a way to bypass that: creating a super user through the Django CLI.

```
docker-compose -f local.yml run --rm django python manage.py createsuperuser
```

Then `http://localhost:8001/admin` and you login with your super user. When you'll come back to the base URL, you'll be logged in and you'll be able to enjoy our Yara rule hunting feature!

**Comment by b-u-g-s** [comment]
Hi and thanks for the quick answer! 
So yes, it worked! :)
Now I have a few more questions though but I guess they are not issues so I will post them into the discussion tab!

**Comment by U039b** [comment]
Hi @b-u-g-s!
Thank you very much for all your feedbacks. Feel free to use the discussion tab if it is more suitable for you.

Regarding authentication, in production we use GitHub authentication, every thing you need to know about 3rd-party authentication is documented in the [All-Auth Django package](https://django-allauth.readthedocs.io/en/latest/providers.html#github).

**Comment by b-u-g-s** [comment]
Hi @U039b !
Thanks for the link.

**Comment by U039b** [comment]
Inactive, I close. Feel free to reopen.
