### ISSUE TITLE
Implement retrohunt for abuse.ch

### ISSUE THREAD

**Issue by evilcel3ri** [Pithus/bazaar#4]
https://twitter.com/abuse_ch/status/1358778140596838401

**Comment by christalib** [comment]
Thinking about it , I'm trying to find a way to do it. Should it, after analysis pull up automated yara rules? Otherwise, if it's just custom yara rules manually uploaded, it could be already done through abuse.ch's website so not really interesting to duplicate the endpoint there. What do you think?

**Comment by Te-k** [comment]
There are multiple questions there I think:
* Is it retrohunt (looking in all the files stored in Pithus) and alerting (analysing new files that are analyzed). Malware Bazar for instance only implements alerts, which is way less complex and heavy to implement. VirusTotal implement both but put some limits to how far back it goes in VT data
* What do you match yara rules on. I guess the easiest is to match on the dex files, but it means you cannot do rules on the manifest and yara data. Koodous has developed [androguard-yara](https://github.com/Koodous/androguard-yara) which allows to match on android data. Not sure if it also matches on strings in the DEX files, and it means that the yara rules are not exportable outside of Pithus mutch.

**Comment by U039b** [comment]
Thank you @christalib and @Te-k!
To make portable Yara rules, it would be possible to implement 2 levels of match:
1. use the Pithus search engine to filter on APK attributes (based on androguard and more)
2. apply Yara rules on all files belonging to the APKs matching 1.

**Comment by evilcel3ri** [comment]
Can we close that issue? @U039b
