### ISSUE TITLE
Bad domain regex

### ISSUE THREAD

**Issue by U039b** [Pithus/bazaar#48]
See the *Network analysis* of https://beta.pithus.org/report/7f4dda8c5131fe4f43112f696c1733bb93d3a9f6bef9e1aa4c87891b49874970

We should probably fix that directly in MobSF.

**Comment by evilcel3ri** [comment]
Ran the sample on MobSF locally didn't recreate the issue. WIll run this on Pithus locally to see if that can be recreated. Otherwise, maybe relaunching the analysis on the sample would do the trick if the bug cannot be reproduced.

**Comment by evilcel3ri** [comment]
Wait, yes it recreates the bug. My bad. Going to look into MoBSF
