### ISSUE TITLE
Calculate hashes for dexofuzzy's returned methods

### ISSUE THREAD

**Issue by evilcel3ri** [Pithus/bazaar#58]

**Comment by evilcel3ri** [comment]
Still working on it, just giving an update.

**Comment by U039b** [comment]
@entropyQueen has implemented the required things in AndroCFG: https://github.com/U039b/AndroCFG/commit/a99552832bc7cc465a5cd5ada838a9ada2c8395d

**Comment by evilcel3ri** [comment]
Oh that's awesome! Good work @entropyQueen, closing this issue then :)
